apiVersion: apps/v1
kind: Deployment
metadata:
  name: myguestbook
  labels:
    app: myguestbook 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myguestbook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myguestbook
    spec:
      containers:
      - image: us.icr.io/sn-labs-christians21/myguestbook:v1
        imagePullPolicy: Always
        name: myguestbook
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
